# -*- coding: utf-8 -*-
"""Data Science Project 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yZFSkSJrBA62d4rz9WgyhfS5uTCU-cDa

# Data Science Project 3 - Customer Segmentation

**Step 1: Import Libraries**
"""

# Import all necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import warnings
warnings.filterwarnings('ignore')

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)

print("✅ All Libraries Imported Successfully!")

"""**Step 2: Load and Explore Data**"""

# IMPORTANT FIX: Use sep='\t' because the data is tab-separated
df = pd.read_csv('Data Science Project 3.csv', sep='\t')

print("=" * 80)
print("📊 DATA OVERVIEW")
print("=" * 80)
print(f"Total customers: {df.shape[0]}")
print(f"Total columns: {df.shape[1]}")

# Look at first few rows
print("\n📄 First 5 Rows of Data:")
print(df.head())

# Check column names
print("\n📋 All Column Names:")
print(df.columns.tolist())

# Check data types
print("\n📊 Data Types:")
print(df.dtypes)

# Check missing values
print("\n🔍 Missing Values in Each Column:")
print(df.isnull().sum())

# Find columns with missing data
print("\n📊 Columns with Missing Data:")
for col in df.columns:
    missing = df[col].isnull().sum()
    if missing > 0:
        print(f"   {col}: {missing} Missing Values")

# Remove rows where Income is missing (now it will work because columns are proper)
df = df.dropna(subset=['Income'])

print(f"\n✅ After Removing Missing Income: {df.shape[0]} Customers Left")

# Display cleaned data
print("\n📄 First 5 Rows After Cleaning:")
print(df.head())

print(f"\n✅ Final Data Shape: {df.shape[0]} Rows, {df.shape[1]} Columns")

"""**Step 3: Select Features for Clustering**"""

# These are the exact column names from your CSV
features = [
    'Income',
    'Kidhome',
    'Teenhome',
    'Recency',
    'MntWines',
    'MntFruits',
    'MntMeatProducts',
    'MntFishProducts',
    'MntSweetProducts',
    'MntGoldProds',
    'NumDealsPurchases',
    'NumWebPurchases',
    'NumCatalogPurchases',
    'NumStorePurchases',
    'NumWebVisitsMonth'
]

# Create feature matrix
X = df[features].copy()

print("=" * 80)
print("🎯 SELECTED FEATURES FOR CLUSTERING")
print("=" * 80)
print(f"Total Features: {len(features)}")
print("\nFeature Names:")
for i, f in enumerate(features, 1):
    print(f"  {i}. {f}")

print(f"\nShape of Feature Matrix: {X.shape}")
print("\n📊 First 5 rows:")
print(X.head())

print("\n📊 Feature Statistics:")
print(X.describe())

"""**Step 4: Scale the Data**"""

# StandardScaler - makes all features equally important
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Convert to DataFrame for easy viewing
X_scaled_df = pd.DataFrame(X_scaled, columns=features)

print("=" * 80)
print("📏 DATA SCALING COMPLETE")
print("=" * 80)
print("✅ Features Standardized (mean=0, std=1)")

print("\n📊 First 5 Rows of Scaled Data:")
print(X_scaled_df.head())

print("\n📊 Scaled Data Statistics:")
print(X_scaled_df.describe())

"""**Step 5: Principal Component Analysis (PCA)**"""

# Apply PCA to reduce dimensions
pca = PCA(n_components=3)
X_pca = pca.fit_transform(X_scaled)

# Also get 2D for visualization
pca_2d = PCA(n_components=2)
X_pca_2d = pca_2d.fit_transform(X_scaled)

# Calculate explained variance
explained_var = pca.explained_variance_ratio_
cumulative_var = np.cumsum(explained_var)

print("=" * 80)
print("📉 PRINCIPAL COMPONENT ANALYSIS (PCA)")
print("=" * 80)

print("Explained Variance by each Component:")
for i, var in enumerate(explained_var, 1):
    print(f"  PC{i}: {var*100:.2f}%")

print(f"\nTotal Variance Explained by 3 Components: {sum(explained_var)*100:.2f}%")
print(f"✅ Reduced {len(features)} Features to 3 Dimensions")

# Visualize PCA variance
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

# Bar plot
ax1.bar(range(1, 4), explained_var * 100, color='skyblue', edgecolor='navy')
ax1.set_xlabel('Principal Component')
ax1.set_ylabel('Variance Explained (%)')
ax1.set_title('Variance Explained by Each PC')
ax1.grid(True, alpha=0.3)

# Cumulative plot
ax2.plot(range(1, 4), cumulative_var * 100, 'ro-', linewidth=2, markersize=8)
ax2.set_xlabel('Number of Components')
ax2.set_ylabel('Cumulative Variance (%)')
ax2.set_title('Cumulative Variance Explained')
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""**Step 6: Elbow Method - Find Optimal K**"""

# Elbow Method - As required in PDF

wcss = []  # Within-Cluster Sum of Squares

print("=" * 80)
print("🎯 ELBOW METHOD - Finding Optimal K")
print("=" * 80)

# Test K from 1 to 12
for k in range(1, 13):
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X_pca)
    wcss.append(kmeans.inertia_)
    print(f"K = {k:2d}: WCSS = {kmeans.inertia_:,.0f}")

# Plot Elbow Method
plt.figure(figsize=(10, 6))
plt.plot(range(1, 13), wcss, 'bo-', linewidth=2, markersize=8)
plt.axvline(x=4, color='r', linestyle='--', label='Elbow at K=4', linewidth=2)
plt.xlabel('Number of Clusters (K)')
plt.ylabel('Within-Cluster Sum of Squares (WCSS)')
plt.title('Elbow Method - Find Optimal Number of Clusters')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

print("\n✅ The 'Elbow' Appears at K = 4")
print("✅ 4 Clusters is optimal based on WCSS")

"""**Step 7: Silhouette Score - Confirm Optimal K**"""

# Silhouette Score - As required in PDF

silhouette_scores = []

print("=" * 80)
print("🎯 SILHOUETTE SCORE - Confirming Optimal K")
print("=" * 80)

for k in range(2, 13):
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(X_pca)
    score = silhouette_score(X_pca, labels)
    silhouette_scores.append(score)
    print(f"K = {k:2d}: Silhouette Score = {score:.4f}")

# Find best K
best_k = np.argmax(silhouette_scores) + 2

# Plot Silhouette Scores
plt.figure(figsize=(10, 6))
plt.plot(range(2, 13), silhouette_scores, 'go-', linewidth=2, markersize=8)
plt.axvline(x=best_k, color='r', linestyle='--', label=f'Best K = {best_k}', linewidth=2)
plt.xlabel('Number of Clusters (K)')
plt.ylabel('Silhouette Score')
plt.title('Silhouette Score - Higher is Better')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

print(f"\n✅ Best K = {best_k} (Silhouette Score: {max(silhouette_scores):.4f})")
print(f"✅ Final Optimal K = {best_k}")

"""**Step 8: Apply K-Means Clustering**"""

# Set optimal K
K = best_k

# Apply K-Means
kmeans = KMeans(n_clusters=K, random_state=42, n_init=10)
df['Cluster'] = kmeans.fit_predict(X_pca)

print("=" * 80)
print("🎯 K-MEANS CLUSTERING COMPLETE")
print("=" * 80)
print(f"Number of Clusters: {K}")

# Cluster distribution
cluster_counts = df['Cluster'].value_counts().sort_index()
print("\n📊 Cluster Distribution:")
for cluster in range(K):
    count = cluster_counts.get(cluster, 0)
    percentage = (count / len(df)) * 100
    print(f"  Cluster {cluster}: {count:4d} Customers ({percentage:5.1f}%)")

# Visualize clusters in 2D
plt.figure(figsize=(12, 8))

colors = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4', '#FFA07A', '#9370DB'][:K]
for cluster in range(K):
    mask = df['Cluster'] == cluster
    plt.scatter(X_pca_2d[mask, 0], X_pca_2d[mask, 1],
               c=colors[cluster], label=f'Cluster {cluster}', alpha=0.6, s=40)

# FIX: Convert 3D centers to 2D
centers_3d = kmeans.cluster_centers_
centers_2d = centers_3d[:, :2]  # Corrected: Take the first two components

plt.scatter(centers_2d[:, 0], centers_2d[:, 1],
           c='red', marker='X', s=200, edgecolors='white', linewidth=2,
           label='Cluster Centers')

plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title(f'Customer Segmentation - {K} Clusters')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

print("\n✅ Clustering and Visualization Complete!")

"""**Step 9: Analyze Cluster Characteristics**"""

# Calculate average values for each cluster
cluster_avg = df.groupby('Cluster')[features].mean()

print("=" * 80)
print("📊 CLUSTER PROFILES (Average Values)")
print("=" * 80)

# Display with formatting
for cluster in range(K):
    row = cluster_avg.loc[cluster]
    print(f"\n{'='*50}")
    print(f"CLUSTER {cluster}")
    print(f"{'='*50}")
    print(f"💰 Income:              ${row['Income']:10,.0f}")
    print(f"👶 Kids at Home:        {row['Kidhome']:10.1f}")
    print(f"🧑 Teens at Home:       {row['Teenhome']:10.1f}")
    print(f"📅 Days Since Purchase: {row['Recency']:10.1f}")
    print(f"🍷 Wine Spending:       ${row['MntWines']:10,.0f}")
    print(f"🍎 Fruit Spending:      ${row['MntFruits']:10,.0f}")
    print(f"🥩 Meat Spending:       ${row['MntMeatProducts']:10,.0f}")
    print(f"🐟 Fish Spending:       ${row['MntFishProducts']:10,.0f}")
    print(f"🍬 Sweet Spending:      ${row['MntSweetProducts']:10,.0f}")
    print(f"💎 Gold Spending:       ${row['MntGoldProds']:10,.0f}")
    print(f"🛒 Deal Purchases:      {row['NumDealsPurchases']:10.1f}")
    print(f"💻 Web Purchases:       {row['NumWebPurchases']:10.1f}")
    print(f"📚 Catalog Purchases:   {row['NumCatalogPurchases']:10.1f}")
    print(f"🏪 Store Purchases:     {row['NumStorePurchases']:10.1f}")
    print(f"🌐 Website Visits:      {row['NumWebVisitsMonth']:10.1f}")

# Heatmap visualization
plt.figure(figsize=(14, 8))
sns.heatmap(cluster_avg, annot=True, fmt='.1f', cmap='coolwarm',
            cbar_kws={'label': 'Average Value'})
plt.title('Cluster Profiles - Average Values by Feature')
plt.xlabel('Features')
plt.ylabel('Cluster')
plt.tight_layout()
plt.show()

"""**Step 10: Create Customer Personas**"""

print("\n" + "=" * 80)
print("👤 CUSTOMER PERSONAS (Business Translation)")
print("=" * 80)

personas = []

for cluster in range(K):
    row = cluster_avg.loc[cluster]

    print(f"\n{'='*50}")
    print(f"CLUSTER {cluster}")
    print(f"{'='*50}")

    # Determine persona based on key characteristics
    if row['Income'] > 70000 and row['MntWines'] > 500:
        persona = "💰 HIGH-VALUE PREMIUM SHOPPER"
        desc = "Affluent customers who spend heavily on premium products"
        strategy = "VIP program, exclusive product access, personalized service"
        emoji = "👑"

    elif row['NumWebPurchases'] > 5 and row['Recency'] < 30:
        persona = "💻 DIGITAL-FIRST SHOPPER"
        desc = "Tech-savvy customers who prefer online shopping"
        strategy = "Mobile app optimization, email marketing, free shipping"
        emoji = "📱"

    elif row['MntMeatProducts'] > 200 and row['Kidhome'] > 0.5:
        persona = "👨‍👩‍👧‍👦 FAMILY SHOPPER"
        desc = "Family-oriented customers buying in bulk"
        strategy = "Family meal deals, bulk discounts, recipe suggestions"
        emoji = "🏠"

    elif row['NumDealsPurchases'] > 3 and row['Income'] < 50000:
        persona = "🎯 DEAL SEEKER"
        desc = "Price-conscious customers looking for discounts"
        strategy = "Discount coupons, flash sales, price match"
        emoji = "🏷️"

    else:
        persona = "🛍️ REGULAR CUSTOMER"
        desc = "Balanced shopping behavior across categories"
        strategy = "General promotions, loyalty program"
        emoji = "⭐"

    personas.append({
        'cluster': cluster,
        'name': persona,
        'description': desc,
        'strategy': strategy,
        'emoji': emoji
    })

    print(f"👤 Persona: {persona}")
    print(f"📝 Description: {desc}")
    print(f"🎯 Strategy: {strategy}")

    print(f"\n📊 Key Stats:")
    print(f"   • Income: ${row['Income']:,.0f}")
    print(f"   • Web Purchases: {row['NumWebPurchases']:.1f}")
    print(f"   • Wine Spend: ${row['MntWines']:.0f}")
    print(f"   • Days Since Purchase: {row['Recency']:.1f}")
    print(f"   • Kids at Home: {row['Kidhome']:.1f}")

"""**Step 11: Final Summary and Save Results**"""

print("\n" + "=" * 80)
print("📈 PROJECT FINAL SUMMARY")
print("=" * 80)

print(f"""
✅ PROJECT COMPLETED SUCCESSFULLY
──────────────────────────────────────────────────────────────────
📊 DATA SUMMARY
   • Total Customers Analyzed: {len(df):,}
   • Features Used for Clustering: {len(features)}
   • PCA Components: 3 (preserved {sum(explained_var)*100:.1f}% variance)

🎯 CLUSTERING RESULTS
   • Optimal Clusters: {K}
   • Best Silhouette Score: {max(silhouette_scores):.4f}
   • Elbow Method Confirmed: K = {K}

👤 CUSTOMER PERSONAS DISCOVERED
""")

for p in personas:
    count = cluster_counts.get(p['cluster'], 0)
    percent = (count / len(df)) * 100
    print(f"   {p['emoji']} Cluster {p['cluster']}: {p['name']}")
    print(f"      • {count} customers ({percent:.1f}%)")
    print(f"      • {p['description']}")

print(f"""
💡 BUSINESS VALUE
   • Targeted marketing campaigns for each segment
   • Personalized product recommendations
   • Optimized marketing budget allocation
   • Improved customer retention strategies

📁 FILES SAVED
   • 'customer_segments_final.csv' - Full data with cluster labels
   • 'cluster_profiles_final.csv' - Average values by cluster
""")

# Save results
df.to_csv('Cleaned Data Science Project 3.csv', index=False)
cluster_avg.to_csv('cluster_profiles_final.csv')

print("✅ Files Saved Successfully!")