# -*- coding: utf-8 -*-
"""Data Science Project 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J4cmspxM-tMtnG1mE8KELJUXViDAy2gH

# **Project 1 - Advanced EDA & Feature Engineering**

**Step 1: Import Libraries**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""**Step 2: Load Dataset**"""

df = pd.read_csv('Data Science Project 1.csv')

"""**Step 3: Dataset Information**"""

print("Shape of Dataset:")
print(df.shape)

print ("\nFirst Five Rows of Dataset:")
print(df.head())

print ("\nLast Five Rows of Dataset:")
print(df.tail())

print("\nColumn of Dataset:")
print(df.columns)

print("\nDataset Information:")
print(df.info())

print("\nStatistical Summary:")
print(df.describe())

"""**Step 4: Check Missing Values**"""

print("Missing Values:")
print(df.isnull().sum())

"""**Step 5: Handle Missing Values**

Since CouponCode is a categorical column, replacing missing values with "No Coupon" is appropriate.
"""

df["CouponCode"].fillna("No Coupon", inplace=True)
print(df.isnull().sum())

"""**Step 6: Convert Date Column**"""

df['Date'] = pd.to_datetime(df['Date'])

"""**Step 7: Outlier Detection (IQR Method)**

Quantity
"""

Q1 = df['Quantity'].quantile(0.25)
Q3 = df['Quantity'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

"""Remove Outliers"""

df=df[(df['Quantity'] >= lower_bound) & (df['Quantity'] <= upper_bound)]
print(df.shape)

"""Repeat for UnitPrice"""

Q1 = df['UnitPrice'].quantile(0.25)
Q3 = df['UnitPrice'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

"""Again Remove Outliers"""

df = df[(df['UnitPrice'] >= lower_bound) & (df['UnitPrice'] <= upper_bound)]
print(df.shape)

"""Repeat for TotalPrice"""

Q1 = df['TotalPrice'].quantile(0.25)
Q3 = df['TotalPrice'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

"""Again Remove Outliers"""

df = df[(df['TotalPrice'] >= lower_bound) & (df['TotalPrice'] <= upper_bound)]
print(df.shape)

"""**Step 8: Feature Engineering**

Feature 1 : Order Month
"""

df['OrderMonth'] = df['Date'].dt.month

"""Feature 2 : Order Year"""

df['OrderYear'] = df['Date'].dt.year

"""Feature 3 : Average Item Price"""

df['AverageItemPrice'] = df['TotalPrice'] / df['Quantity']

"""Feature 4 : Coupon Used"""

df['CouponUsed'] = np.where(df['CouponCode'] == 'No Coupon','No','Yes')

"""Feature 5 : Order Value Category"""

df['OrderValue'] = pd.cut(df['TotalPrice'],
                          bins=[0,100,500,1000,100000],
                          labels=['Low','Medium','High','Premium'])

"""**Step 9: View New Dataset**"""

df.head()

"""**Step 10: Final Missing Values**"""

print(df.isnull().sum())

"""**Step 11: Dataset Shape**"""

print(df.shape)

"""**Step 12: Save Clean Dataset**"""

df.to_csv('Cleaned Data Science Project 1.csv', index=False)

print("Dataset Saved Successfully!")